spring:
  datasource:
    url: jdbc:postgresql://aws-0-eu-north-1.pooler.supabase.com:5432/postgres
    username: postgres.yovamprgzdzixwdlsxzy
    password: Jemoederiseenmooievrouw
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:jwt/app.pub

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  issuer: studdybudy-app
  ttl: 15m
